<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
    <dict>
        <key>items</key>
        <array>
            <dict>
                <key>assets</key>
                <array>
                    <dict>
                        <key>kind</key>
                            <string>software-package</string>
                        <key>url</key>
                        <string>https://${domainName}${downloadPrefix}</string>
                    </dict>
    				<dict>
    					<key>kind</key>
    					<string>full-size-image</string>
    					<key>needs-shine</key>
    					<false/>
    					<key>url</key>
    					<string>https://${domainName}${contextPath}/resources/images/mobile/${icon2x}</string>
    				</dict>
    				<dict>
    					<key>kind</key>
    					<string>display-image</string>
    					<key>needs-shine</key>
    					<false/>
    					<key>url</key>
    					<string>https://${domainName}${contextPath}/resources/images/mobile/${icon}</string>
    				</dict>
                </array>
                <key>metadata</key>
        			<dict>
        				<key>bundle-identifier</key>
        				<string>${buildId}</string>
        				<key>kind</key>
        				<string>software</string>
        				<key>subtitle</key>
        				<string>${brandName}</string>
        				<key>title</key>
        				<string>${brandName}</string>
        			</dict>
            </dict>
        </array>
    </dict>
</plist>